

services:
  flask_app:
    build: .
    ports:
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tubes_rpl_sains_data
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    
